name: Release
on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  releaser:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/go
      GOBIN: ${{ github.workspace }}/go/bin
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ${{ github.workspace }}
      - name: Setup Golang Env
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          cache: true
      - name: View Golang Env
        run: |
          go version
          go env
      - name: Gen Golang Ldflags
        id: genLdflags
        run: |
          CODEREPO="github.com/${{ github.repository }}"
          COMMIT="-X \"${CODEREPO}/config.Version=`git describe --always --no-match --tags --dirty="-dev"`\""
          BUILDTS="-X \"${CODEREPO}/config.BuildTS=`TZ=CST-8 date '+%Y-%m-%d %H:%M:%S'`\""
          GITHASH="-X \"${CODEREPO}/config.GitHash=`git rev-parse HEAD`\""
          GITREF="-X \"${CODEREPO}/config.GitBranch=`git rev-parse --abbrev-ref HEAD`\""
          LDFLAGS="-w -s ${COMMIT} ${BUILDTS} ${GITHASH} ${GITREF}"
          echo "ldflags=${LDFLAGS}" >> $GITHUB_ENV
      - name: Cross Platform Compile
        run: |
          go install src.techknowlogick.com/xgo@latest
          cd ${{ github.workspace }}
          xgo -ldflags='${{ env.ldflags }}' -buildmode=default -dest bin -go go-1.19.x -out=transferdb-${{ github.ref_name }} -targets=linux/amd64,linux/arm64,darwin/arm64,darwin/amd64,windows/amd64 -pkg cmd ${{ github.workspace }}
      - name: Prepare XGO Binary
        run: |
          cd ${{ github.workspace }}
          pwd
          sudo chmod -R 777 bin
          cp example/config.toml bin/
          ls -lnrt ${{ github.workspace }}/bin/
      - name: TAR XGO Binary
        run: |
          cd ${{ github.workspace }}
          tar -zcvf transferdb-${{ github.ref_name }}-linux-amd64.tar.gz bin/transferdb-*-linux-amd64 bin/config.toml
          tar -zcvf transferdb-${{ github.ref_name }}-linux-arm64.tar.gz bin/transferdb-*-linux-arm64 bin/config.toml
          tar -zcvf transferdb-${{ github.ref_name }}-darwin-amd64.tar.gz bin/transferdb-*-darwin-amd64 bin/config.toml
          tar -zcvf transferdb-${{ github.ref_name }}-darwin-arm64.tar.gz bin/transferdb-*-darwin-arm64 bin/config.toml
          tar -zcvf transferdb-${{ github.ref_name }}-windows-amd64.tar.gz bin/transferdb-*-windows-amd64 bin/config.toml
      - name: Build Github Changelog
        id: github_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{steps.github_changelog.outputs.changelog}}
          draft: false
          prerelease: false
          files: |
            transferdb-${{ github.ref }}-linux-amd64.tar.gz
            transferdb-${{ github.ref }}-linux-arm64.tar.gz
            transferdb-${{ github.ref }}-darwin-amd64.tar.gz
            transferdb-${{ github.ref }}-darwin-arm64.tar.gz
            transferdb-${{ github.ref }}-windows-amd64.tar.gz
